### ISSUE TITLE
Agenda widget is always empty

### ISSUE THREAD

**Issue by ransomts** [emacs-dashboard/emacs-dashboard#119]
The dashboard provided agenda widget is empty even though the `C-c a a` agenda command shows items for both the current day and the current week. I have several files in my `agenda-files` variable that these things are being pulled from, how would I go about fixing this?

**Comment by vlurgio** [comment]
This is true for me as well, would love some help with this

**Comment by luksamuk** [comment]
Just a small note, since this might help with a bugfix.

Inserting the agenda widget at any point seemed to "invalidate" everything that comes after it for me (e.g. the footer and any section after the agenda section, including the agenda itself, wouldn't appear).

I narrowed it down to a [specific line](https://github.com/emacs-dashboard/emacs-dashboard/blob/7063ea29edb328fdd5b5206a418a4dcbf39dafda/dashboard-widgets.el#L589) in `dashboard-widgets.el`, which was causing the defect. It seems that `org-compile-prefix-format` was causing a "Selecting deleted buffer" error.

**Comment by flima21** [comment]
It seems to me that this problem has not been solved yet. I can not show the calendar for any items.

**Comment by flima21** [comment]
To show agenda in dasboard the work for me file org
```
*** TODO Take over the world
    DEADLINE: <2019-07-12 Fri>
*** TODO Take over the moon
    DEADLINE: <2019-07-19 Fri>
*** TODO Take over Mars

To show Google calendar not show in dasboarboard because config is events . 

```

**Comment by ransomts** [comment]
fwiw, this has started to work for me. I'll close this out but others should re-open if they'd like to keep reporting
