### ISSUE TITLE
dashboard-mode got disable at emacs startup

### ISSUE THREAD

**Issue by rawr1de** [emacs-dashboard/emacs-dashboard#312]
Not sure if it was the problem, but after installing  "smart-region" package, dashboard initializes as a editable  buffer, and lines are shown as ^L  if dashboard-mode is executed all start working again.

**Comment by jcs090218** [comment]
Hmmm... I guess this is the conflict bug between each packages? I don't see any dubious code in package [smart-region.el](https://github.com/uk-ar/smart-region/blob/master/smart-region.el). Can you try defer `smart-region` package so it's lazy loading? Thanks!

**Comment by rawr1de** [comment]
Just removed smart-region and reinstalled dashboard but still the same

**Comment by rawr1de** [comment]
Fiddling around, somehow I manage to get it working again

**Comment by jcs090218** [comment]
Awesome! Glad you resolved it yourself! :)

**Comment by Bhanukamax** [comment]
> Fiddling around, somehow I manage to get it working again



> Fiddling around, somehow I manage to get it working again

I'm facing the same issue, my dashboard buffer is opening as editable too, do you remember how you managed to fix it?

**Comment by jcs090218** [comment]
Make sure you don't have other plugin interfere the dashboard buffer.

Hope the information helps!

**Comment by Bhanukamax** [comment]
Sure, sounds like some tinkering :) I got this after doing some major refactoring in my config, so I need to go through the commits and see what I did that could affect all buffers, I'll have a look, thanks.

**Comment by teotenn** [comment]
In case it can help somebody, I was having similar issue, my dashboard was editable and `dashboard-mode` was not starting automatically. However, I'm using dashboard for the first time after having a long configuration file for my emacs so, it was not due to a conflicting package. It was rather due to some org file in my agenda directory. I changed the directory path for my org agenda to a clean folder with only one org file and now dashboard is working correctly. 

I wonder what could be the reason for this conflict. Since I am new to dashboard I have no clue, but if you give me some ideas I could perhaps check details in my other org files and try to find out what caused the conflict.

**Comment by jcs090218** [comment]
@ricardoricho is the expert here. Any idea on what could cause this issue? 😕

**Comment by teotenn** [comment]
As soon as I saved the new org file my dashboard failed again. After a few tests I noticed that I can add all the text I want in the org file, but as soon as I add one bullet (`*`) the dashboard crashes again to not loading `dashboard-mode`. I tried disabling all packages that affect my org-mode but nothing has effect. Ass soon as I remove bullets from my org file the dashboard works well (of course, with no agenda).

What is interesting, in Windows it works perfectly. The issue appears in Debian-based linux (SparkyLinux 6.5 based on Debian bullseye). Maybe some dependency(ies) I'm missing?
