### ISSUE TITLE
Dashboard not opening in dashboard-mode.

### ISSUE THREAD

**Issue by apoorv569** [emacs-dashboard/emacs-dashboard#319]
I have been using `emacs-dashboard` for a few months now, it worked fine, until recently, I fresh installed my OS -> `Arch Linux`. Now when I open `Emacs` it opens like this,
![2021-07-27_12-25](https://user-images.githubusercontent.com/53279454/127110019-67f004d9-27c7-41da-a847-fc2558b1243c.png)

And if I go to `dashboard` tab, it looks like this. It opens in `Fundamental` mode for some reason. Also it doesn't show my recent files and projects and all.
![2021-07-27_12-28](https://user-images.githubusercontent.com/53279454/127110041-aae67370-0aea-48d8-9ff7-92b2eee7babb.png)

I have my `Emacs` configuration in a `ORG` document, that I `tangle` to generate a `init.el` file. And for the `emacs-dashboard` section I have this,
```
  (use-package dashboard
    :straight t
    :init                                                                      ;; tweak dashboard config before loading it
    (setq dashboard-set-heading-icons t)                                       ;; add icons for headings
    (setq dashboard-set-file-icons t)                                          ;; add icons for files
    (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")     ;; set a title to be displayed under the banner
    (setq dashboard-startup-banner 'logo)                                      ;; use -official emacs -logo, or text banners -1,2,3
    ;; (setq dashboard-startup-banner "/home/apoorv/.emacs.d/emacs-dash.png")  ;; use custom image as banner
    (setq dashboard-center-content nil)                                        ;; set to 't' for centered content
    (setq dashboard-items '((recents . 5)                                      ;; show some items on dashboard
                            (agenda . 5 )
                            (bookmarks . 5)
                            (projects . 5)
                            (registers . 5)))
    :config
    (dashboard-setup-startup-hook)
    (dashboard-modify-heading-icons '((recents . "file-text")
                                      (bookmarks . "book")))
    :custom
    (custom-set-faces '(dashboard-items-face ((t (:inherit widget-button :weight normal))))))
```

I have tried deleting all cache and packages, and reinstalling from scratch a couple of times. Still doesn't fix anything.

**Comment by jcs090218** [comment]
Is there any error? Try set the variable `debug-on-error` to `t`, and please post the backtrace here! Thanks!

**Comment by apoorv569** [comment]
> Is there any error? Try set the variable `debug-on-error` to `t`, and please post the backtrace here! Thanks!

There was no error. But I think I fixed it. In the `*Messages*` buffer it was saying some file and directories were not found, which I have set for `org-agenda-files`. I created those directories, and it loads fine now. Sorry for the trouble. I'll close this now.

**Comment by Aaronzinhoo** [comment]
@jcs090218  I am actually having a similar issue to this. I dont get any errors on `--debug-init`. I only get message buffer contents here. I am using emacs 29.0.50, which could be the reason for this. My contents are not centered also but I believe these are related

`Loading constants
Done loading constants
Loading defaults
Loading /home/aaronzinho/.emacs.d/custom.el (source)...done
Done loading defaults
Loading straight package manager
Done loading straight package manager
Loading fonts
Done loading fonts
Loading keybindings
Done loading keybindings
Loading utils
Done loading utils
Loading packages
Waiting for git... [2 times]
Loading /home/aaronzinho/.config/emacs/var/recentf-save.el (source)...done
Cleaning up the recentf list...done (0 removed)
.config/emacs/straight/build/dashboard/dashboard.el: Warning: (lambda nil \.\.\.) quoted with ' rather than with #'
[yas] Prepared just-in-time loading of snippets successfully.
.emacs.d/init.el: Warning: (lambda nil \.\.\.) quoted with ' rather than with #'
Created bookmark link.
Created bookmark-other-win link.
tree-sitter-langs: Grammar bundle v0.10.0 was already installed; skipped
Done loading packages
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
Prettier restart complete.
Sunrise 7:00am (PST), sunset 4:57pm (PST) at 33.9N, 118.4W (9:56 hrs daylight)`
