### ISSUE TITLE
feat. Make dashboard footer act like button

### ISSUE THREAD

**Issue by dian-yu-luo** [emacs-dashboard/emacs-dashboard#392]
could I view "dashboard-footer" as a button like "dashboard-navigator-buttons" ? meanwhile, I could add a click event to footer

**Comment by jcs090218** [comment]
It cannot be like button but you can use `add-text-properties` to do similar thing, like:

```elisp
(let* ((footer "enter")
       (keymap (let ((map (make-sparse-keymap)))
                 (define-key map [down-mouse-1]
                             (lambda ()
                               (interactive)
                               (message "click on footer")))
                 map)))
  (add-text-properties 0 (length footer) `(keymap ,keymap mouse-face highlight) footer)
  (setq dashboard-footer-messages (list footer)))
```

**Comment by dian-yu-luo** [comment]
I write some code like this 
```

(defun read-lines (filePath)
  (with-temp-buffer
    (insert-file-contents filePath)
    (split-string (buffer-string) "\n" t)))


(let* (
       (footers (read-lines "~/.emacs.d/learning/emacs/dairy/tipoftheday.org"))
       (footer (nth (random (length footers)) footers ))
       (keymap (let ((map (make-sparse-keymap)))
                 (define-key map [down-mouse-1]
                   (lambda (&rest _)
                     (interactive)
                     (message footer)))
                 map))
       )
  (add-text-properties 0 (length footer) `(keymap ,keymap mouse-face highlight) footer)
  (setq dashboard-footer-messages (list footer)))
```

and show the error
```
Symbol’s value as variable is void: footer
```

**Comment by jcs090218** [comment]
You have footer in a lexical scope, try do it in the global scope!

**Comment by dian-yu-luo** [comment]
but this var was juse referred in this scope, I should not defun a global variable

**Comment by jcs090218** [comment]
When do you get the error? When you click on it? Or when you evaluate it? I need to first understand this issue. 😅

**Comment by dian-yu-luo** [comment]
when click

**Comment by jcs090218** [comment]
> when click

The error is from lexical scope, `footer` get pop out of the stack when `let` operator ended. 

> but this var was just referred in this scope, I should not defun a global variable

Yes, it happens in the scope. But it got pop out after the `let` operator is ended. Your `callback` has assigned to global scope (`keymap`, then to `text-properties`). That's is why `footer` is missing in the callback because it get called somewhere else, not in that scope.

**Comment by dian-yu-luo** [comment]
how to fix?

**Comment by jcs090218** [comment]
You would either need to declare a variable same in the global scope, or forward the variable with the callback itself.

I am closing this issue since this isn't a real feature request, and it's more like a discussion! Feel free to reopen this issue if you insist to have this as a real feature request! Please click a thumb up 👍 in the first post/comment, if anyone want this feature to be built-in.
